apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-monorepo-interceptor
  name: tekton-monorepo-interceptor
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: tekton-monorepo-interceptor
status:
  loadBalancer: {}
