apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
  namespace: tekton-test
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: github-hello-webhook-
        namespace: tekton-test
      spec:
        params:
        - name: gitrepositoryurl
          value: $(tt.params.gitrepositoryurl)
        taskSpec:
          params:
            - name: gitrepositoryurl
              type: string
          steps:
            - name: echo
              image: alpine
              script: |
                echo "Echoing for $URL"
                echo hellooooooooooooo
              env:
                - name: URL
                  value: $(params.gitrepositoryurl)